name: Create Azure Resource Group

on:
  push:
    branches: [ main ]

env:
  AZURE_RG_NAME: my-resource-group
  AZURE_LOCATION: eastus

jobs:
  create-rg:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create --name $AZURE_RG_NAME --location $AZURE_LOCATION
