name: Deploy to Azure SQL Database

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy database to Azure SQL
        uses: azure/sql-action@v1
        with:
          server-name: basic-sql-server.database.windows.net
          connection-string: 'Data Source=basic-sql-server.database.windows.net;Initial Catalog=basic-sql-database;User ID=daniel;Password=1234%asdF'
          sql-file: ./test.sql
